const router = require('express').Router()
const project = require('../model/project')
router.get(['/','/prolist'], project.prolist)
router.get('/work',project.workpage)
router.post('/result',project.result)
router.post('/save',project.save)
router.post('/get_version_all',project.get_version_all)
router.post('/get_version',project.get_version)
router.post('/get_comment',project.get_comment)
router.post('/write_comment',project.write_comment)
router.post('/update_comment',project.update_comment)
router.post('/delete_comment',project.delete_comment)
router.post('/like',project.like)
module.exports = router